### ISSUE TITLE
[bug] `薁` 在化学中读音为 `ào`，而非 `yù`

### ISSUE THREAD

**Issue by Snoopy1866** [Snoopy1866/text-elementalizer#4]
![image](https://github.com/user-attachments/assets/c0135f41-594b-4fd9-993c-3ce453711c52)

**Comment by adproqwq** [comment]
https://github.com/mozillazg/python-pinyin#%E6%8B%BC%E9%9F%B3%E6%9C%89%E8%AF%AF
或许可以通过手动指定字音修复
